### PR TITLE
With Boost 1.74 and newer, use TS executor by default

### LINKED ISSUE #78: Examples fail to build with Boost 1.74
It looks like v1.2.0 is not compatible with ASIO that comes with Boost 1.74, or is there any flags that should be set when configuring ?

```
In file included from /home/debionne/dev/boost/boost_1_74_0/boost/asio/executor.hpp:342,
                 from /home/debionne/dev/boost/boost_1_74_0/boost/asio.hpp:86,
                 from /home/debionne/dev/cli/include/cli/detail/newboostasio.h:33,
                 from /home/debionne/dev/cli/include/cli/detail/boostasio.h:43,
                 from /home/debionne/dev/cli/include/cli/cliasyncsession.h:34,
                 from /home/debionne/dev/cli/examples/asyncsession.cpp:30:
/home/debionne/dev/boost/boost_1_74_0/boost/asio/impl/executor.hpp: In instantiation of ‘void boost::asio::executor::impl<...> >’ has no member named ‘on_work_started’
     executor_.on_work_started();
     ~~~~~~~~~~^~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by sdebionne**
Fixes #78

### CODE REVIEW

**Comment by daniele77** [comment]
Great. Thank you very much @sdebionne

**Comment by sdebionne** [comment]
@daniele77 Any chance to get a `v1.2.1` with this fix, please?

**Comment by daniele77** [comment]
@sdebionne sure.

**Comment by daniele77** [comment]
@sdebionne the release v.1.2.1 has been published (also on vcpkg)

**Comment by killerbot242** [comment]
small question, is a fundamental fix in the pipeline, instead of this define, since that can ripple up, to user code which does not want this define to switch the boost asio back to the past ?

**Comment by sdebionne** [comment]
I am not using Boost.Asio in my project and won't have time to provide a real fix unfortunately. I am not even sure what kind of effort we are talking about...

**Comment by daniele77** [comment]
@killerbot242 @sdebionne I created the issue #89 (remove the symbol BOOST_ASIO_USE_TS_EXECUTOR_AS_DEFAULT) and just fix it in commit 29fef14.
BTW: now the library can use standalone ASIO instead of BOOST ASIO. And, when you don't need remote capabilities, you don't need ASIO at all!
